services:
  jenkins:
    build: .
    image: rentalapp-local-jenkins:lts
    container_name: rentalapp-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: admin123
      GITHUB_USERNAME: ${GITHUB_USERNAME:-anandganapathi22}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
